// =============================================
// Image Studio — Composition Templates
// Layout templates for photo+text compositions
// =============================================

import type { CompositionTemplate, CompositionTemplateId, ImagePlatform } from './types'

// ─── Template Definitions ─────────────────────────────

const quoteCard: CompositionTemplate = {
    id: 'quote-card',
    name: 'Tarjeta Cita',
    description: 'Foto a la izquierda, cita destacada a la derecha con gradiente de marca',
    photoRegion: { x: 0, y: 0, w: 40, h: 100 },
    textRegions: [
        {
            id: 'headline',
            role: 'headline',
            x: 46,
            y: 12,
            w: 48,
            h: 38,
            fontSize: 4.8,
            fontWeight: 800,
            alignment: 'left',
            maxLines: 4,
            color: 'white',
            shadow: false,
        },
        {
            id: 'subtitle',
            role: 'subtitle',
            x: 46,
            y: 54,
            w: 48,
            h: 18,
            fontSize: 2.4,
            fontWeight: 400,
            alignment: 'left',
            maxLines: 3,
            color: 'white',
            shadow: false,
        },
        {
            id: 'attribution',
            role: 'attribution',
            x: 46,
            y: 76,
            w: 48,
            h: 8,
            fontSize: 2.2,
            fontWeight: 700,
            alignment: 'left',
            maxLines: 1,
            color: 'accent',
            shadow: false,
        },
        {
            id: 'slogan',
            role: 'slogan',
            x: 46,
            y: 87,
            w: 48,
            h: 6,
            fontSize: 1.8,
            fontWeight: 400,
            alignment: 'left',
            maxLines: 1,
            color: 'white',
            shadow: false,
        },
    ],
    backgroundType: 'gradient',
    photoOverlay: false,
    platforms: ['linkedin', 'instagram', 'general'],
}

const heroBanner: CompositionTemplate = {
    id: 'hero-banner',
    name: 'Banner Hero',
    description: 'Foto a pantalla completa con overlay gradiente y texto sobre la imagen',
    photoRegion: { x: 0, y: 0, w: 100, h: 100 },
    textRegions: [
        {
            // Headline anchored to bottom so it always kisses the subtitle,
            // regardless of whether it wraps 1, 2 or 3 lines.
            id: 'headline',
            role: 'headline',
            x: 6,
            y: 42, // region opens at 42% — gives headroom for up to 3 lines
            w: 65,
            h: 24, // 42+24 = 66% → bottom edge where text ends
            fontSize: 6.2,
            fontWeight: 900,
            alignment: 'left',
            maxLines: 3,
            color: 'white',
            shadow: true,
            uppercase: true,
            gravity: 'bottom',
        },
        {
            // Subtitle: gravity=bottom so it always touches the divider line,
            // regardless of 1 or 2 lines. Font size increased for impact.
            id: 'subtitle',
            role: 'subtitle',
            x: 6,
            y: 67,
            w: 60,
            h: 12,
            fontSize: 3.2,
            fontWeight: 300,
            alignment: 'left',
            maxLines: 2,
            color: 'white',
            shadow: true,
            gravity: 'bottom',
        },
        {
            // Slogan: 2% after subtitle bottom (79%), uppercase for premium feel
            id: 'slogan',
            role: 'slogan',
            x: 6,
            y: 81,
            w: 45,
            h: 7,
            fontSize: 2.3,
            fontWeight: 700,
            alignment: 'left',
            maxLines: 1,
            color: 'accent',
            shadow: true,
            uppercase: true,
        },
    ],
    backgroundType: 'solid',
    photoOverlay: true,
    platforms: ['x', 'linkedin', 'web', 'general'],
}

const socialSquare: CompositionTemplate = {
    id: 'social-square',
    name: 'Cuadrado Social',
    description: 'Foto arriba, panel con color de marca abajo — ideal para Instagram',
    photoRegion: { x: 0, y: 0, w: 100, h: 55 },
    textRegions: [
        {
            id: 'headline',
            role: 'headline',
            x: 8,
            y: 59,
            w: 84,
            h: 16,
            fontSize: 4.2,
            fontWeight: 800,
            alignment: 'center',
            maxLines: 2,
            color: 'white',
            shadow: false,
        },
        {
            id: 'subtitle',
            role: 'subtitle',
            x: 8,
            y: 77,
            w: 84,
            h: 10,
            fontSize: 2.2,
            fontWeight: 400,
            alignment: 'center',
            maxLines: 2,
            color: 'white',
            shadow: false,
        },
        {
            id: 'slogan',
            role: 'slogan',
            x: 8,
            y: 90,
            w: 84,
            h: 6,
            fontSize: 1.9,
            fontWeight: 700,
            alignment: 'center',
            maxLines: 1,
            color: 'accent',
            shadow: false,
        },
    ],
    backgroundType: 'solid',
    photoOverlay: false,
    platforms: ['instagram', 'general'],
}

const splitVertical: CompositionTemplate = {
    id: 'split-vertical',
    name: 'Split Vertical',
    description: 'Foto a la izquierda 50%, color sólido a la derecha con texto centrado',
    photoRegion: { x: 0, y: 0, w: 50, h: 100 },
    textRegions: [
        {
            id: 'headline',
            role: 'headline',
            x: 55,
            y: 18,
            w: 40,
            h: 28,
            fontSize: 4.2,
            fontWeight: 800,
            alignment: 'center',
            maxLines: 3,
            color: 'white',
            shadow: false,
        },
        {
            id: 'subtitle',
            role: 'subtitle',
            x: 55,
            y: 50,
            w: 40,
            h: 16,
            fontSize: 2.2,
            fontWeight: 400,
            alignment: 'center',
            maxLines: 3,
            color: 'white',
            shadow: false,
        },
        {
            id: 'attribution',
            role: 'attribution',
            x: 55,
            y: 70,
            w: 40,
            h: 8,
            fontSize: 2.1,
            fontWeight: 700,
            alignment: 'center',
            maxLines: 1,
            color: 'accent',
            shadow: false,
        },
        {
            id: 'slogan',
            role: 'slogan',
            x: 55,
            y: 82,
            w: 40,
            h: 6,
            fontSize: 1.8,
            fontWeight: 400,
            alignment: 'center',
            maxLines: 1,
            color: 'white',
            shadow: false,
        },
    ],
    backgroundType: 'solid',
    photoOverlay: false,
    platforms: ['linkedin', 'x', 'general'],
}

const frameBranded: CompositionTemplate = {
    id: 'frame-branded',
    name: 'Marco de Marca',
    description: 'Foto centrada con marco/borde en colores de campaña y texto abajo',
    photoRegion: { x: 8, y: 5, w: 84, h: 65 },
    textRegions: [
        {
            id: 'headline',
            role: 'headline',
            x: 8,
            y: 72,
            w: 84,
            h: 11,
            fontSize: 3.6,
            fontWeight: 800,
            alignment: 'center',
            maxLines: 2,
            color: 'white',
            shadow: false,
        },
        {
            id: 'subtitle',
            role: 'subtitle',
            x: 8,
            y: 84,
            w: 84,
            h: 7,
            fontSize: 2.0,
            fontWeight: 400,
            alignment: 'center',
            maxLines: 1,
            color: 'white',
            shadow: false,
        },
        {
            id: 'slogan',
            role: 'slogan',
            x: 8,
            y: 93,
            w: 84,
            h: 5,
            fontSize: 1.8,
            fontWeight: 700,
            alignment: 'center',
            maxLines: 1,
            color: 'accent',
            shadow: false,
        },
    ],
    backgroundType: 'gradient',
    photoOverlay: false,
    platforms: ['instagram', 'linkedin', 'x', 'tiktok', 'general'],
}

// ─── Registry ─────────────────────────────────────────

export const COMPOSITION_TEMPLATES: CompositionTemplate[] = [
    quoteCard,
    heroBanner,
    socialSquare,
    splitVertical,
    frameBranded,
]

/** Obtiene un template por su ID. */
export function getCompositionTemplate(id: CompositionTemplateId): CompositionTemplate | undefined {
    return COMPOSITION_TEMPLATES.find((t) => t.id === id)
}

/** Filtra templates compatibles con una plataforma. */
export function getTemplatesForPlatform(platform: ImagePlatform): CompositionTemplate[] {
    return COMPOSITION_TEMPLATES.filter((t) => t.platforms.includes(platform))
}
